[node]
detect-drivers = false

[relay]
url = "https://user:key@ondemand.us-west-1.saucelabs.com:443/wd/hub"
status-endpoint = "/status"
configs = [
  "10", '{"browserName": "chrome", "platformName": "Windows 11"}',
  "10", '{"browserName": "firefox", "platformName": "Windows 11"}',
  "10", '{"browserName": "MicrosoftEdge", "platformName": "Windows 11"}',
  "10", '{"browserName": "chrome", "platformName": "macOS 13"}',
  "10", '{"browserName": "firefox", "platformName": "macOS 13"}',
  "10", '{"browserName": "MicrosoftEdge", "platformName": "macOS 13"}',
  "10", '{"browserName": "Safari", "platformName": "macOS 13"}',
  "10", '{"browserName": "chrome", "platformName": "Linux"}',
  "10", '{"browserName": "firefox", "platformName": "Linux"}'
]