name: Tests on Grid with Video

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Create assets directory and change permissions
        run: cd grid && mkdir assets && sudo chown 1200:1201 assets
      - name: Run tests with docker compose
        run: docker compose -f docker-compose-local-video.yml up --build --abort-on-container-exit --timeout 30
      - name: Upload test assets
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-assets
          path: ./grid/assets/